"""Migrate

Revision ID: 89aa6d98df30
Revises: c62daf0f458b
Create Date: 2025-05-16 23:52:49.165290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89aa6d98df30'
down_revision = 'c62daf0f458b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_mimetype', sa.String(length=200), nullable=True))
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_user_phone', ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_phone', type_='unique')
        batch_op.alter_column('avatar',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('avatar_mimetype')

    # ### end Alembic commands ###
